version: '3'

services:

  dockergen:
    image: jwilder/nginx-proxy:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - ./certs:/etc/nginx/certs
#      - certs:/etc/nginx/certs
      - /var/run/docker.sock:/tmp/docker.sock:ro
    environment:
      - DHPARAM_GENERATION=0


volumes:
  conf:
  vhost:
  html:
#  certs:

# Do not forget to 'docker network create nginx-proxy' before launch, and to add '--network nginx-proxy' to proxied containers. 

#networks:
#  default:
#    external:
#      name: nginx-proxy
